### ISSUE TITLE
May need more dependencies

### ISSUE THREAD

**Issue by huytd** [siddharthkp/reaqt#1]
I follow the instruction to create a new project, install `reaqt`, and when I run with:

```
npm run dev
```

It threw some error that said I missed the `babel`, `babel-loader`, `babel-preset-es2015`, `babel-preset-react`,...

After I install these packages, it's worked fine.

So, it seems like we missed these packages, should we add it along with the package just like `webpack`, `react`, `react-dom`?

**Comment by siddharthkp** [comment]
@huytd Sorry, missed this somehow!

Yep, you are right, pull request is welcome 😄

**Comment by siddharthkp** [comment]
Fixed in 1.2.3
