### ISSUE TITLE
Not ReaQt?

### ISSUE THREAD

**Issue by polarathene** [siddharthkp/reaqt#11]
I'm looking for what was talked about [here](https://www.youtube.com/watch?v=p8re60C3Huw), which uses React with Qt under the hood. They termed it ReaQt but this doesn't seem to have anything to do with Qt? :(

I wouldn't have expected to come across a project with a module name like this that didn't involve Qt :P

**Comment by siddharthkp** [comment]
Haha, sorry for the confusion. Totally coincidental
