### ISSUE TITLE
why reaqt instead react

### ISSUE THREAD

**Issue by shalinikarkera** [siddharthkp/reaqt#6]
I know its a dumb question but something disturbing :P 
Even on commands (npm install reaqt --save), any particular reason.

**Comment by siddharthkp** [comment]
short answer: react was already taken?

better answer: reaqt is a wrapper around react. It simplifies the tooling/conventions required with react to create performant applications.

Does that answer your question, or did I understand it incorrectly?

**Comment by shalinikarkera** [comment]
Oh!! U mean there is package cld reaqt......sorry was not aware..!!!

**Comment by siddharthkp** [comment]
yep, you're looking at it 😄 

I should probably add a nice description.

**Comment by shalinikarkera** [comment]
Huh..!! you are  some other level of coder:P.Anyhow thanx for me knowing it.:)
