### ISSUE TITLE
npm install reaqt error

### ISSUE THREAD

**Issue by shalinikarkera** [siddharthkp/reaqt#9]
Hi, facing this error while installing  npm install reaqt --save

E:\sid-proj>npm install reaqt --save
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\KSHALI3\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "reaqt" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.1
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "reaqt" under a package
npm ERR! also called "reaqt". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\sid-proj\npm-debug.log

**Comment by siddharthkp** [comment]
I think the project where you're trying to install this is also named `reaqt`.

npm does not allow that because that will lead to a circular dependency.

**Comment by shalinikarkera** [comment]
Nope, I saw that and changed the name.

**Comment by siddharthkp** [comment]
```
npm ERR! Refusing to install package with name "reaqt" under a package
npm ERR! also called "reaqt". Did you name your project the same
npm ERR! as the dependency you're installing?
```

The error you posted seems to be old, can you share your `package.json` file

**Comment by shalinikarkera** [comment]
Thanku, working I forgot to update the package.json

**Comment by shalinikarkera** [comment]
When I do npm run dev
E:\sid-proj>npm run dev

> sid-proj@1.3.1 dev E:\sid-proj
> reaqt dev

 PAGES  Defining routes...

fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'E:\sid-proj\pages'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at getPages (E:/sid-proj/node_modules/reaqt/dev/server.js:29:20)
    at Object.<anonymous> (E:/sid-proj/node_modules/reaqt/dev/server.js:36:1)
    at Module._compile (module.js:570:32)
    at loader (E:\sid-proj\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\sid-proj\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\sid-proj\node_modules\reaqt\index.js:17:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\KSHALI3\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! sid-proj@1.3.1 dev: `reaqt dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sid-proj@1.3.1 dev script 'reaqt dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sid-proj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     reaqt dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sid-proj
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sid-proj
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\sid-proj\npm-debug.log

**Comment by shalinikarkera** [comment]
Failing at reaqt dev script...aam I doing anything wrong...Added the script in package.json

**Comment by siddharthkp** [comment]
You need to make a folder called `pages` and add your pages into that.

Reference: https://github.com/siddharthkp/reaqt#pages

**Comment by siddharthkp** [comment]
Do you think I should make a `getting started` page as well? The readme doesn't have direct instructions, only concepts.

**Comment by shalinikarkera** [comment]
Oh ok. Thought , this project should be running with few sample pages. Found pages created in example folder.

**Comment by shalinikarkera** [comment]
I think can be updated it in Readme only.
